---
- name: bootstrap local vagrant-host
  hosts: local
  tasks:
    - name: install base packages
      package:
        name:
          - curl
          - net-tools
          - openssh-server
          - vim
          - git
      become: yes
    - name: copy sshd_config
      copy:
        dest: /etc/ssh/sshd_config
        src: files/sshd_config
        owner: root
        group: root
        mode: 644
      become: yes
      notify:
        - Restart OpenSSH
    - name: create directory needed for binaries
      file:
        path: ./tmp
        state: directory
    - name: download virtualbox binary
      get_url:
        url: https://download.virtualbox.org/virtualbox/5.2.22/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb
        dest: ./tmp
    - name: install virtualbox binary
      apt:
        deb: ./tmp/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb
      become: yes
    - name: download vagrant binary
      get_url:
        url: https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
        dest: ./tmp
    - name: install vagrant binary
      apt:
        deb: ./tmp/vagrant_2.2.2_x86_64.deb
      become: yes

  handlers:
    - name: Restart OpenSSH
      service: name=ssh state=restarted

